[package]
name = "inputmodule"
version = "1.0.0"
authors = ["games869"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
skyline = { git = "https://github.com/ultimate-research/skyline-rs.git" }
skyline_smash = { git = "https://github.com/ultimate-research/skyline-smash.git", features = ["weak_l2cvalue"] }
