[package]
name = "inputmodule"
version = "1.0.0"
authors = ["games869"]
edition = "2018"
description = "A library for helping make the creation of custom motion and charge inputs for super smash bros ultimate more accessible"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
skyline = { git = "https://github.com/ultimate-research/skyline-rs.git" }
skyline_smash = { git = "https://github.com/ultimate-research/skyline-smash.git" }
